### ISSUE TITLE
在插件中使用context.getApplicationContext()时会有个非常严重的问题

### ISSUE THREAD

**Issue by FreemanQ** [FinalLody/Direct-Load-apk#10]
因为插件中使用context.getApplicationContext()取到的是主程序的application，这时候使用它去获取插件中的Resources其实是找不到的，会抛出一个android.content.res.Resources$NotFoundException，这也是为什么我之前使用在插件中用第三方组件会报错的原因。
但是很多应用都会有使用context.getApplicationContext去获取资源文件的习惯，请问这个地方该怎么处理呢？是不是fillPluginApplication这个方法得采用新的方式去做呢？
@FinalLody

**Comment by FinalLody** [comment]
修复很简单，你给Application 手动 attach 一个自己的 baseContext，这个baseContext 继承 ContextWarpper，传入的base要为宿主的ApplicationContext，然后复写它的getResources , getAssets，getClassLoader。

**Comment by FreemanQ** [comment]
唉，盼星星盼月亮终于等到你的回复了！真是太感谢了！
我今天一来就试了你上面说的方法，可是怎么搞都不对，然后我换了一种方式，居然可以了，但是总感觉做的不太对，下面是我的思路，再次麻烦你看下，多谢了！
如果在创建application的时候attach一个baseContext，感觉这个baseContext始终都不会被用到。
因为插件activity在准备启动的时候，control会调用插件activity的attach方法，这个时候传入了代理activity作为该方法的第一个参数，这样插件activity的mBase就被赋值成了宿主的activity，结果到了插件里面调用getApplicationContext还是取不到resources。
如果在调用插件activity的attach方法时就把自定义的这个baseContext作为第一个参数传进去，那么这个baseContext就是有效的，不过在复写getResources , getAssets，getClassLoader这三个方法的时候，试了好多种途径，怎么写都不对。
后来我就换了一种方式，结果居然可以了！但是总感觉哪里有点不对，下面是我实现的代码：

======================================================
下面是PluginActivityControl中的dispatchProxyToPlugin方法
======================================================
public void dispatchProxyToPlugin(LAPK apk) {

        if (plugin.getBaseContext() != null) { return; }
        try	{
            //Finals 修改以前的注入方式，采用原生的方式
        	//Freeman 有关Activity的attach方法，请查看源码
            Instrumentation mInstrumentation = proxyRef.get("mInstrumentation");
            pluginRef.call(
                    // 方法名
                    "attach",
                    // Context context
                    // proxy,
                    new LPluginBaseContext(proxy), // 看这里！！！！！！！！！！！！！！！！
                    // ActivityThread aThread
                    proxyRef.get("mMainThread"),
                    // Instrumentation instr
                    new LPluginInstrument(mInstrumentation),
                    // IBinder token
                    proxyRef.get("mToken"),
                    // int ident
                    proxyRef.get("mEmbeddedID") ==null ? 0:proxyRef.get("mEmbeddedID"),
                    // Application application
                    app == null ? proxy.getApplication() : app,
                    // Intent intent
                    proxy.getIntent(),
                    // ActivityInfo info
                    proxyRef.get("mActivityInfo"),
                    // CharSequence title
                    proxy.getTitle(),
                    // Activity parent
                    proxy.getParent(),
                    // String id
                    proxyRef.get("mEmbeddedID"),
                    // NonConfigurationInstances lastNonConfigurationInstances
                    proxy.getLastNonConfigurationInstance(),
                    // Configuration config
                    proxyRef.get("mCurrentConfig"));

            pluginRef.set("mWindow", proxy.getWindow());
			plugin.getWindow().setCallback(plugin);
			Reflect.on(proxy.getBaseContext()).call("setOuterContext",plugin);

		} catch (ReflectException e) {
			e.printStackTrace();
		}
    }

======================================================
下面是自定义baseContext
======================================================

package com.lody.plugin.api;

import android.content.Context;
import android.content.ContextWrapper;

import com.lody.plugin.bean.LAPK;

public class LPluginBaseContext extends ContextWrapper{
	
	private Context context;
	
	public LPluginBaseContext(Context base) {
		super(base);
		this.context = base;
	}

	@Override
	public Context getApplicationContext() {
		return context;
	}

}

**Comment by FinalLody** [comment]
之所以取不到资源是因为你没有复写LPluginBaseContext 的 getAssets和getResources方法

**Comment by FreemanQ** [comment]
只是复写了LPluginBaseContext 的 getAssets和getResources方法还不够，还要在attach Activity的时候，把当前LPluginBaseContext传递进去，这样就不会被proxy的ContextWrapper覆盖掉。
