### ISSUE TITLE
发现master的源码中PluginActivityControl类的方法有错误

### ISSUE THREAD

**Issue by FreemanQ** [FinalLody/Direct-Load-apk#9]
在master的插件源码中，PluginActivityControl 这个类的第200行方法是不是写错了？
/**
     * 执行插件的onStart方法
     * @see android.app.Activity#onStart()
     */
    @Override
    public void callOnStart()
	{
        //getPluginRef().call("onStart");
		i.callActivityOnStop(plugin);
    }
是不是把 i.callActivityOnStart(plugin); 写成了 i.callActivityOnStop(plugin); 
@kymjs @FinalLody ？？？

**Comment by FinalLody** [comment]
是写错了。
